create table weather_data (
    id int primary key generated by default as identity,
    temperature real not null,
    wind_speed real not null,
    atmospheric_pressure real not null,
    air_humidity real not null,
    weather_conditions varchar(50) not null,
    weather_location varchar(50) not null,
    weather_date date not null
)